meta_product_name: "Irdane"
meta_title: "Irdane - Portfolio"
meta_description: "You can discovered my work, website, graphic design and even more!"
meta_image: "Logo Irdane.png"                           # Une image dans votre dossier app/assets/images/
twitter_account: ""
